backend:
  name: github
  repo: garba-the-analyst/my-portfolio
  branch: main

media_folder: "src/assets/images"
public_folder: "/assets/images"

collections:
  - name: "projects"
    label: "Portfolio Projects"
    folder: "src/content/projects"
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - {
          label: "Technologies (Comma separated)",
          name: "technologies",
          widget: "string",
        }
      - {
          label: "Project Image",
          name: "image",
          widget: "image",
          required: false,
        }
      - {
          label: "GitHub Link",
          name: "github",
          widget: "string",
          required: false,
        }

  - name: "about"
    label: "About & Profile"
    files:
      - file: "src/_data/about.yml"
        name: "about_info"
        label: "Profile Information"
        fields:
          - { label: "Profile Picture", name: "profile_pic", widget: "image" }
          - { label: "Bio Statement", name: "bio", widget: "text" }
